### ISSUE TITLE
License incompatible with upstream Dracut (GPLv3 vs GPLv2)

### ISSUE THREAD

**Issue by ddiss** [MADhacking/rbd-dracut-module#1]
Hi,

I'd like to test and eventually propose your RBD module for inclusion in upstream Dracut. However, this is not currently possible due to your use of GPLv3, instead of GPLv2 as used by upstream Dracut:
https://git.kernel.org/pub/scm/boot/dracut/dracut.git/tree/COPYING

Please consider changing your licence to GPLv2.

**Comment by HackingM** [comment]
Hi David,

That would be great!

I have changed the license as requested.

Do let me know how your testing goes and if there is anything I can do to assist.

Thanks!
